only_rules:
  - array_init
  - block_based_kvo
  - closing_brace
  - closure_parameter_position
  - closure_spacing
  - colon
  - comma
  - control_statement
  - custom_rules
  - discarded_notification_center_observer
  - discouraged_direct_init
  - dynamic_inline
  - empty_enum_arguments
  - empty_parameters
  - empty_parentheses_with_trailing_closure
  - explicit_init
  - implicit_getter
  - is_disjoint
  - joined_default_parameter
  - leading_whitespace
  - legacy_cggeometry_functions
  - legacy_constant
  - legacy_constructor
  - legacy_nsgeometry_functions
  - mark
  - multiline_parameters
  - nimble_operator
  - opening_brace
  - operator_usage_whitespace
  - overridden_super_call
  - private_action
  - private_over_fileprivate
  - private_unit_test
  - prohibited_super_call
  - protocol_property_accessors_order
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - redundant_discardable_let
  - redundant_nil_coalescing
  - redundant_string_enum_value
  - redundant_void_return
  - required_enum_case
  - return_arrow_whitespace
  - single_test_class
  - statement_position
  - trailing_newline
  - trailing_semicolon
  - trailing_whitespace
  - unneeded_break_in_switch
  - unused_closure_parameter
  - unused_enumerated
  - unused_optional_binding
  - valid_ibinspectable
  - vertical_whitespace
  - void_return
  - weak_delegate
  - yoda_condition
