name: SwiftLint

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint:
    name: SwiftLint
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/realm/swiftlint:0.49.1

    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: SwiftLint
        run: swiftlint --reporter github-actions-logging --strict
